language: minimal

addons:
  apt:
    packages:
      - luarocks
      - realpath

git:
  depth: 150

install: luarocks install --local luacheck

script: /home/travis/.luarocks/bin/luacheck . --no-color -q

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then ./wowace_translations.sh; fi
  - ./generate_changelog.sh
  - sed -i "s/@build-time@/`date +%Y%m%d%H%M%S`/" WeakAuras/Init.lua
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash; if [[ $? != 0 ]]; then TRAVIS_TEST_RESULT=1; fi
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 1.13.2 -m .pkgmeta-classic -w 24944; if [[ $? != 0 ]]; then TRAVIS_TEST_RESULT=1; fi

after_script: if [[ "$TRAVIS_TEST_RESULT" == 1 ]]; then curl -s https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh | bash -s -- failure $WEBHOOK_URL; fi

notifications:
  email:
    on_failure: always
    on_success: never
