name: CI-Beta

on:
  push:
    branches:
      - bc
    tags:
      - "**-alpha**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 500

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning

      - name: Generate Changelog
        run: ./generate_changelog.sh

      - name: Update Build Date
        run: sed -i "s/@build-time@/`date +%Y%m%d%H%M%S`/" WeakAuras/Init.lua

      - name: Create Package
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: BigWigsMods/packager@master
        with:
          args: -g bc -m .pkgmeta-bc
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      - name: Create Artifact
        if: github.event_name == 'push' && !contains(github.ref, 'refs/tags/')
        uses: BigWigsMods/packager@master
        with:
          args: -z -g bc -m .pkgmeta-bc

      - uses: actions/upload-artifact@v2
        with:
          name: WeakAuras-BC
          path: .release/

      - name: Send Status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          status: ${{ job.status }}
        if: failure()
